version: "3"
 
services:
  php:
    build:
      context: ./php
    image: "xr-vue/php:latest"
    hostname: "xr-vue-php"
    volumes:
      - ..:/app:cached
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
      - ./php/ssmtp.conf:/etc/ssmtp/ssmtp.conf:cached
    working_dir: /app

  nginx:
    build:
      context: ./nginx
    image: "xr-vue/nginx:latest"
    hostname: "xr-vue-nginx"
    ports:
      - "8081:8081"
    volumes:
      - ..:/app:cached
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - php